homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 6
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

## Logging Settings ##
logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Cloud service
#cloud:

http:
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

## Config Includes ##
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
binary_sensor: !include binary_sensor.yaml

## InfluxDB database ##
influxdb:
  host: !secret nas_hostname
  port: 8086
  database: home_assistant

## MQTT Broker ##  
mqtt:
  broker: !secret mqtt_ip_address
  discovery: true

## Xiaomi Bridge ##
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_hub_key

## Digital Ocean VPS ##    
digital_ocean:
  access_token: !secret digital_ocean_api

group:
## VIEWS ##
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.woonkamer
      - group.meterkast
      - group.sonarr
      - group.radarr
  Nas_view:
    view: yes
    name: Synology
    entities:
      - group.nas
  Netwerk_view:
    view: yes
    name: Netwerk
    entities:
    - group.network
## GROUPS ##      
  Woonkamer:
    name: Woonkamer
    control: hidden
    entities:
      - switch.mediacenter
      - sensor.mediacenter
      - switch.computers
      - sensor.computers
      - sensor.livingroom_temperature
  Meterkast:
    name: Meterkast
    entities:
      - sensor.temperature_158d0001ab24f9
      - sensor.humidity_158d0001ab24f9
      - binary_sensor.door_window_sensor_158d0001dbd397
  Nas:
    name: Synology
    entities:
      - sensor.cpu_load_total
      - sensor.memory_usage_real
      - sensor.network_up
      - sensor.network_down
      - sensor.temperature_sdb
      - sensor.temperature_sdc
      - sensor.temperature_sdd
      - sensor.temperature_sde
      - sensor.volume_used_volume_2
      - sensor.volume_used_volume_3
  Network:
    name: Netwerk
    entities:
      - sensor.fritz_netmonitor
      - sensor.uptime
      - sensor.externalip
      - sensor.downloaded
      - sensor.uploaded
  Sonarr:
    name: Upcoming Series
      - sensor.sonarr_upcoming
  Radarr:
    name: Upcoming Movies
      - sensor.radarr_upcoming